package com.main.app.dtos.Creature;

import java.util.List;

public record CreatureDTO(
        String key,
        String name,
        CreatureDocument document,
        CreatureType type,
        CreatureSize size,
        Float challengeRating,
        Integer proficiencyBonus,
        CreatureSpeed speed,
        CreatureSpeed speedAll,
        String category,
        String subcategory,
        String alignment,
        CreatureLanguages languages,
        Integer armorClass,
        String armorDetail,
        Integer hitPoints,
        String hitDice,
        Integer experiencePoints,
        AbilityScores abilityScores,
        AbilityScores modifiers,
        Integer initiativeBonus,
        AbilityScores savingThrows,
        AbilityScores savingThrowsAll,
        SkillBonuses skillBonuses,
        SkillBonuses skillBonusesAll,
        Integer passivePerception,
        ResistancesAndImmunities resistancesAndImmunities,
        Integer normalSightRange,
        Integer darkvisionRange,
        Integer blindsightRange,
        Integer tremorsenseRange,
        Integer truesightRange,
        List<CreatureAction> actions,
        List<CreatureTrait> traits,
        List<String> creatureSets,
        List<NamedReference> environments,
        CreatureIllustration illustration,
        CrossReferences crossreferences
) {
}
