-- Sharing by email. An invitation is bound to one email address; it is accepted when someone signs in with that address
-- and the sign-in service says they've verified it. Until then it's a pending row, which the owner can see and cancel.

-- The email address a user has proved they own (the token's email, when its email_verified claim is true).
ALTER TABLE open5e.users ADD COLUMN verified_email text;

CREATE INDEX users_verified_email_idx ON open5e.users (verified_email);

CREATE TABLE open5e.document_invitations (
    id           bigint      GENERATED BY DEFAULT AS IDENTITY,
    document_key text        NOT NULL,
    email        text        NOT NULL,
    role         text        NOT NULL,
    invited_by   bigint      NOT NULL,
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    CONSTRAINT document_invitations_pkey PRIMARY KEY (id),
    CONSTRAINT document_invitations_email_unique UNIQUE (document_key, email),
    CONSTRAINT document_invitations_email_check CHECK (email = lower(email)),
    CONSTRAINT document_invitations_role_check CHECK (role IN ('VIEWER', 'EDITOR')),
    CONSTRAINT document_invitations_document_key_fk FOREIGN KEY (document_key) REFERENCES open5e.documents (key) ON DELETE CASCADE,
    CONSTRAINT document_invitations_invited_by_fk FOREIGN KEY (invited_by) REFERENCES open5e.users (id) ON DELETE CASCADE
);

CREATE INDEX document_invitations_email_idx ON open5e.document_invitations (email);
