-- Player characters: the people a table plays, kept on a user's account so they can be dropped into an initiative
-- order. The owner makes and manages one; it can name the user who plays it, who then sees it and can keep its numbers
-- up to date. Not Open5e content, and not in a document: nothing here is shared the way homebrew is.

CREATE TABLE open5e.player_characters (
    id               bigint      GENERATED BY DEFAULT AS IDENTITY,
    owner_id         bigint      NOT NULL,
    played_by        bigint,
    name             text        NOT NULL,
    ruleset          text        NOT NULL,
    class_key        text,
    class_name       text,
    species_key      text,
    species_name     text,
    level            integer     NOT NULL DEFAULT 1,
    armor_class      integer,
    hit_points       integer,
    initiative_bonus integer     NOT NULL DEFAULT 0,
    notes            text,
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT player_characters_pkey PRIMARY KEY (id),
    CONSTRAINT player_characters_ruleset_check CHECK (ruleset IN ('5e-2014', '5e-2024')),
    CONSTRAINT player_characters_level_check CHECK (level BETWEEN 1 AND 20),
    CONSTRAINT player_characters_owner_id_fk FOREIGN KEY (owner_id) REFERENCES open5e.users (id) ON DELETE CASCADE,
    CONSTRAINT player_characters_played_by_fk FOREIGN KEY (played_by) REFERENCES open5e.users (id) ON DELETE SET NULL
);

CREATE INDEX player_characters_owner_id_idx ON open5e.player_characters (owner_id);
CREATE INDEX player_characters_played_by_idx ON open5e.player_characters (played_by);
